### ISSUE TITLE
Bug nel body

### ISSUE THREAD

**Issue by franciscopablorusso** [franciscopablorusso/franciscopablorusso.github.io#1]
### Problema
- Compare una fastidiosa barra per swippare la pagina a destra e la linea nera che delimita la navbar si interrompe;

### RIchiesta
🐞 rendere la linea nera continua eliminando questa fastidiosa barra di scrolling da sinistra verso destra

**Comment by GianlucaMarano** [comment]
Problema risolto, ti ho fatto una pull request
